# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac0379083e9686e5871672c333d71bacadd489c89dd1ae96eaece5b49bffa96dc43bd09ee47ea9113c6693789ba88634b9b3b99cdaa19c49b51c81cee923ad07

test:
  secret_key_base: 4442f22eb0eda48694b95d06b30af36157d114a42b306b3335a276a5594e3d91d3a1a0f894ec49f9dcaedb3f4821dddb81db1f2a46a10fbb468e49f2af8b30cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
